\d alert
\d alert_email
\d attachment
\d channel
\d channel_alert
\d channel_statistics
\d code_template
\d configuration
\d configuration_sequence
\d encryption_key
\d event
\d event_sequence
\d message
\d message_sequence
\d person
\d person_sequence
\d preferences
\d schema_info
\d script
\d template
