\d configurations
\d devices
\d devices_device_id_seq
\d exams
\d exams_exam_id_seq
\d hipaa_audit_accession_numbers
\d hipaa_audit_accession_numbers_id_seq
\d hipaa_audit_mrns
\d hipaa_audit_mrns_id_seq
\d hipaa_audit_views
\d hipaa_audit_views_id_seq
\d job_sets
\d job_sets_job_set_id_seq
\d jobs
\d jobs_job_id_seq
\d patient_merge_events
\d patient_merge_events_event_id_seq
\d patients
\d patients_patient_id_seq
\d reports
\d reports_report_id_seq
\d roles
\d schema_version
\d schema_version_id_seq
\d status_codes
\d studies
\d studies_study_id_seq
\d transactions
\d transactions_transaction_id_seq
\d users
\d users_user_id_seq
\d v_exam_status
\d v_job_status
