#!/bin/csh
set NEW_PATH=/usr/local/edgeserver-3.2_New-Install/torquebox-3.x.incremental.1870/jboss/standalone/tmp/vfs
set             UPGRADE_PATH=/usr/local/edgeserver/torquebox-3.x.incremental.1870/jboss/standalone/tmp/vfs

foreach f ( \
  openam-shared-11.0.0.jar \
  commons-logging-api-1.1.jar \
  openam-xacml3-schema-11.0.0.jar \
  openam-idpdiscovery-11.0.0.jar \
  org.restlet.ext.jackson-2.1.1.jar \
  cc_zh_TW-2008-08-08.jar \
  ST4-4.0.7.jar \
  openam-dtd-schema-11.0.0.jar \
  openam-mib-schema-11.0.0.jar \
  webservices-rt-2009-29-07.jar \
  authapi-2005-08-12.jar \
  dcm4che-net-2.0.26.jar \
  openam-auth-oauth2-11.0.0.jar \
  jsr311-api-1.1.1.jar \
  jaxrpc-spi-1.1.3_01.jar \
  forgerock-authz-filter-1.2.0.jar \
  org.restlet.osgi-org.restlet-2.1.1.jar \
  openam-authz-filter-11.0.0.jar \
  prep-content-3.2.0-t1.jar \
  jersey-client-1.1.5.2.jar \
  cc_es-2008-08-08.jar \
  cc_it-2008-08-08.jar \
  openam-dashboard-11.0.0.jar \
  openam-wsfederation-schema-11.0.0.jar \
  openam-auth-cert-11.0.0.jar \
#  activation-1.1.jar \
  cc_zh-2008-08-08.jar \
  forgerock-jaspi-container-1.2.0.jar \
  xercesImpl-2.11.0.jar \
  cc_sv-2008-08-08.jar \
  jaxp-api-1.4.2.jar \
  openam-auth-ad-11.0.0.jar \
  xml-serializer-2.11.0.jar \
  org.restlet.osgi-org.restlet.ext.json-2.1.1.jar \
  isorelax-20030108.jar \
  commons-collections-3.2.1.jar \
  openam-saml2-schema-11.0.0.jar \
  aopalliance-1.0.jar \
  commons-cli-1.2.jar \
  openam-auth-httpbasic-11.0.0.jar \
  json-web-token-2.0.2.jar \
  grizzly-framework-2.3.4.jar \
  org.osgi.core-4.0.0.jar \
  velocity-1.7.jar \
  antlr-runtime-3.5.jar \
  dcm4che-tool-dcmecho-2.0.28.jar \
  json-fluent-2.0.2.jar \
  openam-cli-impl-11.0.0.jar \
  xml-apis-2.11.0.jar \
  cc_fr-2008-08-08.jar \
  org.restlet.jse-org.restlet-2.1.1.jar \
  openam-core-11.0.0.jar \
  openam-cli-definitions-11.0.0.jar \
  json-resource-2.0.2.jar \
  jato-2005-05-04.jar \
  esapiport-2009-26-07.jar \
  openam-datastore-11.0.0.jar \
  postgresql-8.4-702.jdbc4.jar \
  openam-coretoken-11.0.0.jar \
  publicsuffix-1.0.1.jar \
  openam-auth-radius-11.0.0.jar \
  openam-auth-hotp-11.0.0.jar \
  openam-server-auth-ui-11.0.0.jar \
  openam-auth-persistentcookie-11.0.0.jar \
  i18n-core-1.4.0.jar \
  OpenFM-11.0.0.jar \
  openam-federation-library-11.0.0.jar \
  xalan-2.7.1.jar \
  org.restlet.osgi-org.restlet.lib.org.json-2.0.jar \
  freemarker-2.3.19.jar \
  openam-auth-datastore-11.0.0.jar \
  oauth-client-1.1.5.2.jar \
  openam-jaxrpc-schema-11.0.0.jar \
  openam-auth-msisdn-11.0.0.jar \
  openam-authn-filter-modules-11.0.0.jar \
  openam-auth-adaptive-11.0.0.jar \
  click-nodeps-2.3.0.jar \
  openam-auth-deviceprint-module-11.0.0.jar \
  openam-auth-nt-11.0.0.jar \
  jackson-core-asl-1.9.7.jar \
  org.restlet.jse-org.restlet.ext.json-2.1.1.jar \
#  xml-resolver-2.11.0.jar \
  slf4j-log4j12-1.6.1.jar \
  openam-authfilter-shared-11.0.0.jar \
  click-extras-2.3.0.jar \
  javax.mail-1.5.1.jar \
  webservices-extra-2008-03-12.jar \
  openam-auth-ldap-11.0.0.jar \
  relaxngDatatype-20020414.jar \
  json-resource-servlet-2.0.2.jar \
  openam-ldap-utils-11.0.0.jar \
  openam-common-auth-ui-11.0.0.jar \
  openam-auth-oath-11.0.0.jar \
  openam-auth-windowsdesktopsso-11.0.0.jar \
  forgerock-util-1.1.0.jar \
  xsdlib-20060615.jar \
#  log4j-1.2.16.jar \
  commons-fileupload-1.2.2.jar \
  java-ipv6-0.14.jar \
  oauth-server-1.1.5.2.jar \
  openam-forgerock-rest-11.0.0.jar \
#  activation-1.1.jar \
  jaxrpc-impl-1.1.3_01-041406.jar \
  jstl-1.1.2.jar \
  openam-oauth2-core-token-service-11.0.0.jar \
#  log4j-1.2.16.jar \
  json-20090211.jar \
  cc_ja-2008-08-08.jar \
  webservices-extra-api-2003-09-04.jar \
  openam-auth-common-11.0.0.jar \
  commons-codec-1.6.jar \
  openam-oauth2-common-11.0.0.jar \
  commons-lang-2.4.jar \
  openam-oauth2-main-11.0.0.jar \
  commons-io-2.3.jar \
  forgerock-auth-filter-common-1.2.0.jar \
  commons-logging-1.1.3.jar \
  guice-3.0.jar \
  antlr-2.7.7.jar \
  org.restlet.ext.freemarker-2.1.1.jar \
  cc_de-2008-08-08.jar \
  slf4j-api-1.6.1.jar \
  openam-oauth2-restlet-extension-11.0.0.jar \
  javax.security.auth.message-3.1.jar \
  je-5.0.73.jar \
  openam-auth-jdbc-11.0.0.jar \
  openam-entitlements-11.0.0.jar \
  openam-rest-11.0.0.jar \
  openam-auth-securid-11.0.0.jar \
  commons-lang-2.6.jar \
  json-patch-1.0.0.jar \
  c3p0-0.9.1.2.jar \
  openam-oauth-11.0.0.jar \
  forgerock-jaspi-jwt-session-module-1.2.0.jar \
  geoip-1.2.8.jar \
  opendj-server-2.6.0.jar \
  openam-auth-anonymous-11.0.0.jar \
  jasypt-1.9.1.jar \
  webservices-api-2009-14-01.jar \
  openam-auth-membership-11.0.0.jar \
  cc-2008-08-08.jar \
  opendj-ldap-sdk-2.6.4.jar \
  dcm4che-core-2.0.26.jar \
  openam-liberty-schema-11.0.0.jar \
  openam-authn-filter-config-11.0.0.jar \
  openam-auth-application-11.0.0.jar \
  serializer-2.7.1.jar \
  org.restlet.ext.servlet-2.1.1.jar \
  openam-idsvcs-schema-11.0.0.jar \
  jss4-2007-08-11.jar \
  stringtemplate-3.2.1.jar \
  org.restlet.jse-org.restlet.lib.org.json-2.0.jar \
  ognl-2.6.9.jar \
  mail-1.4.5.jar \
  jaxrpc-api-1.1.jar \
  jersey-bundle-1.1.1-ea.jar \
  commons-io-1.4.jar \
  openam-annotations-11.0.0.jar \
  oauth-signature-1.1.5.2.jar \
  slf4j-api-1.7.2.jar \
  openam-oauth2-openam-extension-11.0.0.jar \
  org.forgerock.json.resource-1.2.2.jar \
  javax.inject-1.jar \
  jsoup-1.7.3.jar \
  cc_zh_HK-2008-08-08.jar \
  cc_ko-2008-08-08.jar \
  cc_zh_CN-2008-08-08.jar \
  jdmkrt-2007-01-10.jar \
  core-3.2.0-t1.jar \
  jackson-mapper-asl-1.9.7.jar \
 )
#  echo $f
#  echo diff -q  $NEW_PATH/*/*/$f $UPGRADE_PATH/*/*/$f
  diff -q  $NEW_PATH/*/*/$f $UPGRADE_PATH/*/*/$f
end

foreach f ( \
  db/seeds.rb \
  README \
  Rakefile \
  pom.xml \
  target/dependency-maven-plugin-markers/org.rsna.isn-torquebox-zip-3.x.incremental.1870.marker \
  META-INF/MANIFEST.MF \
  app/views/sessions/new.html.erb \
  app/views/retrieve_content/index.html.erb \
  app/views/patients/_results.html.erb \
  app/views/patients/_blank_search_term.html.erb \
  app/views/patients/_consent_dialog.html.erb \
  app/views/patients/create_rsna_id.html.erb \
  app/views/patients/index.html.erb \
  app/views/patients/xds_export.html.erb \
  app/views/patients/xds_import.html.erb \
  app/views/users/_reset_password_form.html.erb \
  app/views/users/new.html.erb \
  app/views/users/roles.html.erb \
  app/views/users/_user_bar.html.erb \
  app/views/users/change_password.html.erb \
  app/views/layouts/_tabs.html.erb \
  app/views/layouts/application.html.erb \
  app/views/layouts/print.html.erb \
  app/views/exams/_results.html.erb \
  app/views/exams/search.html.erb \
  app/views/exams/show_cart.html.erb \
  app/views/exams/print_site_to_site_info.html.erb \
  app/views/exams/retry_job.html.erb \
  app/views/exams/_token_info.html.erb \
  app/views/exams/print_patient_info.html.erb \
  app/views/exams/index.html.erb \
  app/views/exams/_token_dialog.html.erb \
  app/views/edge_configurations/_form.html.erb \
  app/views/edge_configurations/new.html.erb \
  app/views/edge_configurations/index.html.erb \
  app/views/edge_configurations/edit.html.erb \
  app/views/devices/_form.html.erb \
  app/views/devices/new.html.erb \
  app/views/devices/index.html.erb \
  app/views/devices/edit.html.erb \
  app/views/admin/audit.html.erb \
  app/views/admin/_paginator.html.erb \
  app/views/admin/_paginated_results.html.erb \
  app/views/admin/_audit_details.html.erb \
  app/views/admin/_transaction_list.html.erb \
  app/views/admin/_paginator_buttons.html.erb \
  app/views/tail/index.html.erb \
  app/views/email_configurations/edit_email_configuration.html.erb \
  app/views/email_configurations/test.html.erb \
  app/helpers/application_helper.rb \
  app/helpers/devices_helper.rb \
  app/helpers/documents_helper.rb \
  app/helpers/edge_configurations_helper.rb \
  app/controllers/sessions_controller.rb \
  app/controllers/devices_controller.rb \
  app/controllers/users_controller.rb \
  app/controllers/exams_controller.rb \
  app/controllers/email_configurations_controller.rb \
  app/controllers/configuration_methods.rb \
  app/controllers/application_controller.rb \
  app/controllers/admin_controller.rb \
  app/controllers/patients_controller.rb \
  app/controllers/tail_controller.rb \
  app/controllers/edge_configurations_controller.rb \
  app/controllers/retrieve_content_controller.rb \
  app/assets/images/IMageShareLogo.png \
  app/assets/images/footer-background.png \
  app/assets/images/reverse-tab-right.png \
  app/assets/images/print-button-background.png \
  app/assets/images/dialog-background.png \
  app/assets/images/footer.png \
  app/assets/images/header-background-purple.png \
  app/assets/images/rsna-image-share.png \
  app/assets/images/title-gradient.png \
  app/assets/images/reverse-tab-left.png \
  app/assets/images/rsna-edge.png \
  app/assets/images/button-background.png \
  app/assets/images/header-background.png \
  app/assets/images/footer-hand.png \
  app/assets/images/print-header.jpg \
  app/assets/images/nibib-logo.png \
  app/assets/images/asc.gif \
  app/assets/images/ajax-loader.gif \
  app/assets/images/rails.png \
  app/assets/images/desc.gif \
  app/assets/javascripts/iframe.js \
  app/assets/javascripts/application.js \
  app/assets/javascripts/slate.js \
  app/assets/javascripts/slate/bootswatch.js \
  app/assets/javascripts/slate/loader.js \
  app/assets/javascripts/pages/email_configuration.js \
  app/assets/javascripts/pages/cart.js \
  app/assets/javascripts/pages/test_email.js \
  app/assets/javascripts/stuff.js \
  app/assets/stylesheets/sti-edge.css \
  app/assets/stylesheets/print_layout.css \
  app/assets/stylesheets/application.css \
  app/assets/stylesheets/slate.css \
  app/assets/stylesheets/slate/base.less \
  app/assets/stylesheets/slate/loader.css.less \
  app/assets/stylesheets/slate/bootswatch.css.less \
  app/assets/stylesheets/slate/mixins.less \
  app/assets/stylesheets/slate/variables.less \
  app/models/exam.rb \
  app/models/patient.rb \
  app/models/view_exam_status.rb \
  app/models/report_author.rb \
  app/models/job.rb \
  app/models/device.rb \
  app/models/job_transaction.rb \
  app/models/hipaa_accession_number.rb \
  app/models/email_configuration.rb \
  app/models/user.rb \
  app/models/job_set.rb \
  app/models/hipaa_mrn.rb \
  app/models/search.rb \
  app/models/status_code.rb \
  app/models/hipaa_view.rb \
  app/models/edge_configuration.rb \
  app/models/rsna_id.rb \
  app/models/view_job_status.rb \
  app/models/report.rb \
  lib/sso.rb \
  lib/rsna_tables.rb \
  lib/tasks/torquebox.rake \
  lib/hipaa_filter/tasks/hipaa_log_tasks.rake \
  lib/hipaa_filter/test/hipaa_log_test.rb \
  lib/hipaa_filter/hipaa_filter/hipaa_log.rb \
  lib/hipaa_filter/spec/test_body.rb \
  lib/restful-authentication/LICENSE \
  lib/restful-authentication/Rakefile \
  lib/restful-authentication/tasks/auth.rake \
  lib/restful-authentication/restful-authentication.gemspec \
  lib/restful-authentication/TODO \
  lib/restful-authentication/lib/trustification.rb \
  lib/restful-authentication/lib/authorization/aasm_roles.rb \
  lib/restful-authentication/lib/authorization/stateful_roles.rb \
  lib/restful-authentication/lib/trustification/email_validation.rb \
  lib/restful-authentication/lib/authentication/by_cookie_token.rb \
  lib/restful-authentication/lib/authentication/by_password.rb \
  lib/restful-authentication/lib/authorization.rb \
  lib/restful-authentication/lib/authentication.rb \
  lib/restful-authentication/rails/init.rb \
  lib/restful-authentication/CHANGELOG \
  lib/restful-authentication/generators/authenticated/authenticated_generator.rb \
  lib/restful-authentication/generators/authenticated/USAGE \
  lib/restful-authentication/generators/authenticated/lib/insert_routes.rb \
  lib/restful-authentication/generators/authenticated/templates/model_controller.rb \
  lib/restful-authentication/generators/authenticated/templates/authenticated_test_helper.rb \
  lib/restful-authentication/generators/authenticated/templates/controller.rb \
  lib/restful-authentication/generators/authenticated/templates/features/accounts.feature \
  lib/restful-authentication/generators/authenticated/templates/features/sessions.feature \
  lib/restful-authentication/generators/authenticated/templates/features/step_definitions/user_steps.rb \
  lib/restful-authentication/generators/authenticated/templates/features/step_definitions/rest_auth_features_helper.rb \
  lib/restful-authentication/generators/authenticated/templates/features/step_definitions/ra_navigation_steps.rb \
  lib/restful-authentication/generators/authenticated/templates/features/step_definitions/ra_response_steps.rb \
  lib/restful-authentication/generators/authenticated/templates/features/step_definitions/ra_resource_steps.rb \
  lib/restful-authentication/generators/authenticated/templates/features/step_definitions/ra_env.rb \
  lib/restful-authentication/generators/authenticated/templates/helper.rb \
  lib/restful-authentication/generators/authenticated/templates/site_keys.rb \
  lib/restful-authentication/generators/authenticated/templates/_model_partial.html.erb \
  lib/restful-authentication/generators/authenticated/templates/test/model_functional_test.rb \
  lib/restful-authentication/generators/authenticated/templates/test/mailer_test.rb \
  lib/restful-authentication/generators/authenticated/templates/test/unit_test.rb \
  lib/restful-authentication/generators/authenticated/templates/test/functional_test.rb \
  lib/restful-authentication/generators/authenticated/templates/activation.erb \
  lib/restful-authentication/generators/authenticated/templates/signup_notification.erb \
  lib/restful-authentication/generators/authenticated/templates/observer.rb \
  lib/restful-authentication/generators/authenticated/templates/login.html.erb \
  lib/restful-authentication/generators/authenticated/templates/authenticated_system.rb \
  lib/restful-authentication/generators/authenticated/templates/model.rb \
  lib/restful-authentication/generators/authenticated/templates/migration.rb \
  lib/restful-authentication/generators/authenticated/templates/model_helper_spec.rb \
  lib/restful-authentication/generators/authenticated/templates/model_helper.rb \
  lib/restful-authentication/generators/authenticated/templates/mailer.rb \
  lib/restful-authentication/generators/authenticated/templates/signup.html.erb \
  lib/restful-authentication/generators/authenticated/templates/spec/fixtures/users.yml \
  lib/restful-authentication/generators/authenticated/templates/spec/helpers/users_helper_spec.rb \
  lib/restful-authentication/generators/authenticated/templates/spec/controllers/access_control_spec.rb \
  lib/restful-authentication/generators/authenticated/templates/spec/controllers/users_controller_spec.rb \
  lib/restful-authentication/generators/authenticated/templates/spec/controllers/authenticated_system_spec.rb \
  lib/restful-authentication/generators/authenticated/templates/spec/controllers/sessions_controller_spec.rb \
  lib/restful-authentication/generators/authenticated/templates/spec/models/user_spec.rb \
  lib/restful-authentication/notes/RailsPlugins.txt \
  lib/restful-authentication/notes/SecurityFramework.graffle \
  lib/restful-authentication/notes/Trustification.txt \
  lib/restful-authentication/notes/Authorization.txt \
  lib/restful-authentication/notes/Authentication.txt \
  lib/restful-authentication/notes/Tradeoffs.txt \
  lib/restful-authentication/notes/AccessControl.txt \
  lib/restful-authentication/notes/SecurityPatterns.txt \
  lib/restful-authentication/notes/SecurityFramework.png \
  lib/restful-authentication/README.textile \
  lib/assets/javascripts/shadedborder/license.txt \
  lib/assets/javascripts/shadedborder/grad.png \
  lib/assets/javascripts/shadedborder/simple.html \
  lib/assets/javascripts/shadedborder/back.jpg \
  lib/assets/javascripts/shadedborder/grad2.png \
  lib/assets/javascripts/shadedborder/shadedborder.js \
  lib/assets/javascripts/shadedborder/grad3.png \
  lib/assets/javascripts/shadedborder/test.html \
  lib/assets/javascripts/jquery.tablesorter.min.js \
  license \
  config/initializers/active_record_backgroundable.rb \
  config/initializers/isn.rb \
  config/initializers/session_store.rb \
  config/initializers/cookies_serializer.rb \
  config/initializers/inflections.rb \
  config/initializers/mime_types.rb \
  config/initializers/site_keys.rb \
  config/initializers/rsna_rails.rb \
  config/initializers/wrap_parameters.rb \
  config/initializers/backtrace_silencers.rb \
  config/initializers/filter_parameter_logging.rb \
  config/initializers/assets.rb \
  config/initializers/hippa_filter.rb \
  config/warble.rb \
  config/database.yml \
  config/torquebox.rb \
  config/secrets.yml \
  config/locales/en.yml \
  config/environments/test.rb \
  config/environments/production.rb \
  config/environments/development.rb \
  config/application.rb \
  config/boot.rb \
  config/environment.rb \
  config/routes.rb \
)
#  echo $NEW_PATH/temp*/token-app.knob*/$f
#  echo diff -q $NEW_PATH/temp*/token-app.knob*/$f $UPGRADE_PATH/temp*/token-app.knob*/$f
  diff -q $NEW_PATH/temp*/token-app.knob*/$f $UPGRADE_PATH/temp*/token-app.knob*/$f

end

